- name: Add docker CE repository
  command: dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo

- name: Install Docker CE
  command: dnf install docker-ce -y --nobest --allowerasing

- name: Start docker
  systemd: 
    name: docker
    state: started
    enabled: yes

- name: Finding out the latest docker-compose version
  shell: curl -s https://api.github.com/repos/docker/compose/releases/latest | grep 'tag_name' | cut -d\" -f4
  register: compose_version

- name: Install docker-compose
  get_url: 
    url : https://github.com/docker/compose/releases/download/{{ compose_version.stdout }}/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 'u+x,g+x'

- name: Install Python Docker module
  command: pip3 install docker

- name: Install Python docker-compose module
  command: pip3 install docker-compose
